### ISSUE TITLE
Error parsing AST:  TypeError: Cannot read property 'type' of undefined at parseNode 

### ISSUE THREAD

**Issue by mhartington** [billyvg/tigris.nvim#10]
Getting an error when opening a JS file

Error from nvim log file
<details>

```
neovim.api.nvim_buf_get_lines: import React from 'react';,import ReactDOM from 'react-dom';,import './index.css';,import App from './App';,import registerServiceWorker from './registerServiceWorker';,,ReactDOM.render(<App />, document.getElementById('root'));,registerServiceWorker();
2017-08-11T00:49:22.730Z - debug: request -> neovim.api.nvim_buf_add_highlight
2017-08-11T00:49:22.731Z - debug: response -> neovim.api.nvim_buf_add_highlight: 1
2017-08-11T00:49:22.731Z - info: [tigris.js] new id: 1, number
2017-08-11T00:49:22.731Z - info: [tigris.js] [index.js/1] Calling tigris parser
2017-08-11T00:49:22.762Z - info: [tigris.js] Error parsing AST:  TypeError: Cannot read property 'type' of undefined
    at parseNode (/Users/mhartington/.config/nvim/repos/github.com/billyvg/tigris.nvim/rplugin/node/tigris.js/node_modules/vim-syntax-parser/lib/index.js:37:31)
    at parseRange (/Users/mhartington/.config/nvim/repos/github.com/billyvg/tigris.nvim/rplugin/node/tigris.js/node_modules/vim-syntax-parser/lib/index.js:91:21)
    at ImportDeclaration (/Users/mhartington/.config/nvim/repos/github.com/billyvg/tigris.nvim/rplugin/node/tigris.js/node_modules/vim-syntax-parser/lib/index.js:192:7)
    at NodePath._call (/Users/mhartington/.config/nvim/repos/github.com/billyvg/tigris.nvim/rplugin/node/tigris.js/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/mhartington/.config/nvim/repos/github.com/billyvg/tigris.nvim/rplugin/node/tigris.js/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/mhartington/.config/nvim/repos/github.com/billyvg/tigris.nvim/rplugin/node/tigris.js/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/mhartington/.config/nvim/repos/github.com/billyvg/tigris.nvim/rplugin/node/tigris.js/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/mhartington/.config/nvim/repos/github.com/billyvg/tigris.nvim/rplugin/node/tigris.js/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/mhartington/.config/nvim/repos/github.com/billyvg/tigris.nvim/rplugin/node/tigris.js/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/mhartington/.config/nvim/repos/github.com/billyvg/tigris.nvim/rplugin/node/tigris.js/node_modules/babel-traverse/lib/index.js:114:17)
2017-08-11T00:49:22.762Z - debug: request -> neovim.api.nvim_call_function
2017-08-11T00:49:24.182Z - debug: response -> neovim.api.nvim_call_function: 0
```

</details>

Steps to reproduce.

- `npm i -g create-react-app`
- `create-react-app sample-app && cd sample-app
- `nvim src/index.js`

<img width="1680" alt="screen shot 2017-08-10 at 8 55 37 pm" src="https://user-images.githubusercontent.com/2835826/29198014-48fcf464-7e0e-11e7-95f4-cb4dd8755379.png">

**Comment by billyvg** [comment]
This project has been largely ignored, but I just pushed something to fix this https://github.com/billyvg/vim-syntax-parser/commit/373d92fb3cfc45cf9b1ac8eb85b937d9fceabfe0

Let me know if this project ends up semi-useful to you and I can pick it back up :)
